# Numpy - Numerical Python

In [1]:
# de facto standard
import numpy as np

1. ndarray(Numpy Dimensional Array)

In [2]:
a = np.array([1, 4, 5, 8], float)
print(a)

[1. 4. 5. 8.]


In [3]:
a[3], a.dtype, a.shape

(8.0, dtype('float64'), (4,))

2. Array shape

In [4]:
# 1차원 - vector
a = np.array([1, 4, 5, 8], float)

In [5]:
# 2차원 - matrix
m = [[1, 4], [5, 8]]
b = np.array(m, float)
print(b)

[[1. 4.]
 [5. 8.]]


In [6]:
# 3차원 - tensor
t = [[[1, 4], [5, 8]], [[11, 14], [15, 18]]]
c = np.array(t, float)
c

array([[[ 1.,  4.],
        [ 5.,  8.]],

       [[11., 14.],
        [15., 18.]]])

In [7]:
a.shape, b.shape, c.shape

((4,), (2, 2), (2, 2, 2))

In [8]:
# ndim
a.ndim, b.ndim, c.ndim

(1, 2, 3)

In [9]:
# size
a.size, b.size, c.size

(4, 4, 8)

In [10]:

# data type(dtype)
c = np.array(t, dtype=np.float32)
c

array([[[ 1.,  4.],
        [ 5.,  8.]],

       [[11., 14.],
        [15., 18.]]], dtype=float32)

- reshape: size는 동일

In [12]:
c.reshape(2, 4).shape

(2, 4)

In [13]:
c.reshape(2, 4)

array([[ 1.,  4.,  5.,  8.],
       [11., 14., 15., 18.]], dtype=float32)

In [14]:
c.reshape(8,)

array([ 1.,  4.,  5.,  8., 11., 14., 15., 18.], dtype=float32)

In [15]:
# -1은 한번만 사용 가능
c.reshape(-1, 4)

array([[ 1.,  4.,  5.,  8.],
       [11., 14., 15., 18.]], dtype=float32)

In [16]:
# flatten - 1차원으로 변환 flatten - 1차원으로 변환
c.flatten()
c.flatten()

array([ 1.,  4.,  5.,  8., 11., 14., 15., 18.], dtype=float32)

### 3. Indexing and Slicing

In [17]:
a = np.arange(6)        # a = np.array(range(6))
a

array([0, 1, 2, 3, 4, 5])

In [18]:
a = np.arange(6).reshape(2, 3)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [19]:
a[0][1], a[0, 1]        # 행 인덱스, 열 인덱스

(1, 1)

In [20]:
# 리스트와는 달리 행, 열 모두에 대해 슬라이싱 가능
a[:, :2]

array([[0, 1],
       [3, 4]])

In [21]:
b = np.arange(16).reshape(-1, 4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [22]:
# 5, 6, 9, 10
b[1:3, 1:3]

array([[ 5,  6],
       [ 9, 10]])

In [23]:
# 0, 1, 4, 5, 8, 9
b[:3, :2]

array([[0, 1],
       [4, 5],
       [8, 9]])

In [24]:
# 세번째 열까지는 X, 마지막 열은 Y
X, Y = b[:, :-1], b[:, -1]
X.shape, Y.shape

((4, 3), (4,))

### 4. Creation

In [25]:
# arange
np.arange(1, 10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
np.arange(0, 1.1, 0.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [27]:
# 실수는 우리가 원하는 값을 정확하게 표현하지 못함
np.arange(0, 1.1, 0.1).tolist()[3] == 0.3

False

In [28]:
# 두 실수의 비교는 차이가 아주 작냐를 물어보는 것이 올바른 방법임
np.abs(np.arange(0, 1.1, 0.1).tolist()[3] - 0.3) < 1e-8

True

In [29]:
# ones, zeros, empty
a = np.zeros((5,), dtype=np.int8)
a

array([0, 0, 0, 0, 0], dtype=int8)

In [30]:
b = np.ones((2, 4), dtype=np.int8)
b

array([[1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int8)

In [31]:
np.empty((2, 5))

array([[0.1, 0.2, 0.3, 0.4, 0.5],
       [0.6, 0.7, 0.8, 0.9, 1. ]])

In [32]:
a = np.arange(24).reshape(4, -1)
np.ones_like(a)

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

In [33]:

np.zeros_like(a)

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [34]:
# 단위 행렬: identity
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [35]:
# eye - 대각선이 1인 행렬
np.eye(3, 5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [36]:
np.eye(N=3, M=5, k=-1)

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.]])

In [37]:
np.eye(3, 5, 2)

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

- Random sampling

In [39]:
np.random.seed(2021)

# 균등 분포
np.random.uniform(0, 1, 10).reshape(2, 5)

array([[0.60597828, 0.73336936, 0.13894716, 0.31267308, 0.99724328],
       [0.12816238, 0.17899311, 0.75292543, 0.66216051, 0.78431013]])

In [40]:
# 정규 분포
np.random.normal(0, 1, 10).reshape(2, 5)

array([[ 0.10641374,  0.42215483,  0.12420684, -0.83795346,  0.4090157 ],
       [ 0.10275122, -1.90772239,  1.1002243 , -1.40232506, -0.22508127]])

In [41]:
# 이항분포, 포아송분포(poisson), t-분포(standard_t), F-분포(f)
np.random.binomial(100, 0.5, 10)

array([46, 53, 57, 48, 57, 44, 40, 57, 54, 49])