# Numpy - Numerical Python

In [2]:
# de Facto standard
import numpy as np

#### ndarray(Numpy Dimensional Array)

In [4]:
a = np.array([1, 4, 5, 8], float)
print(a)

[1. 4. 5. 8.]


In [5]:
a[3], a.dtype, a.shape

(8.0, dtype('float64'), (4,))

#### Array shape

In [8]:
# 1차원은 보통 vector
a = np.array([1, 4, 5, 8], float)

In [10]:
# 2차원 -matrix
m = [[1,4],[5,8]]
b = np.array(m, float)
b

array([[1., 4.],
       [5., 8.]])

In [11]:
# 3차원 - tensor
t = [[[1,4],[5,8],[11,14],[15,18]]]
c = np.array(t,float)
c

array([[[ 1.,  4.],
        [ 5.,  8.],
        [11., 14.],
        [15., 18.]]])

In [12]:
a.shape, b.shape, c.shape

((4,), (2, 2), (1, 4, 2))

In [13]:
# ndim
a.ndim, b.ndim, c.ndim

(1, 2, 3)

In [14]:
# size
a.size, b.size, c.size

(4, 4, 8)

In [15]:
# data type(dtype)


- reshape : size는 동일

In [18]:
c.reshape(2,4).shape

(2, 4)

In [19]:
c.reshape(2,4)

array([[ 1.,  4.,  5.,  8.],
       [11., 14., 15., 18.]])

In [20]:
c.reshape(8,)

array([ 1.,  4.,  5.,  8., 11., 14., 15., 18.])

In [21]:
# -1은 한번만 사용사능
c.reshape(-1,4)

array([[ 1.,  4.,  5.,  8.],
       [11., 14., 15., 18.]])

In [22]:
#flatten - 1차원으로 변환
c.flatten()

array([ 1.,  4.,  5.,  8., 11., 14., 15., 18.])

#### INdexing and Slicing

In [26]:
a = np.arange(6)  # ===   a = np.array(range(6)) 와 같다.
a

array([0, 1, 2, 3, 4, 5])

In [28]:
a = np.arange(6).reshape(2,3)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [32]:
a[0][1], a[0,1] #행 인덱스, 열인덱스

(1, 1)

In [33]:
a[:,:2]

array([[0, 1],
       [3, 4]])

In [36]:
b = np.arange(16).reshape(-1,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [37]:
# 5, 6, 9,10
b[1:3, 1:3]

array([[ 5,  6],
       [ 9, 10]])

In [39]:
# 0,1,4,5,8,9
b[:3,:2]

array([[0, 1],
       [4, 5],
       [8, 9]])

In [40]:
# 세번째 열까지는 x, 마지막 열은 y
x,y = b[:, :-1],b[:,-1]
x.shape, y.shape

((4, 3), (4,))

#### Creation

In [42]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
np.arange(0,1.1,0.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [44]:
np.arange(0,1.1,0.1).tolist()

[0.0,
 0.1,
 0.2,
 0.30000000000000004,
 0.4,
 0.5,
 0.6000000000000001,
 0.7000000000000001,
 0.8,
 0.9,
 1.0]

In [45]:
# 실수는 우리가 원하값을 정확하게 표현하지 못함
np.arange(0,1.1,0.1).tolist()[3] == 0.3

False

In [47]:
# 두 실수의 비교는 차이가 아주 작나를 물어보는 것이 올바른 방법임
np.abs(np.arange(0,1.1,0.1).tolist()[3] - 0.3) < 1e-8

True

In [50]:
# ones, zeros, empty
a= np.zeros((5,), dtype=np.int8)
a

array([0, 0, 0, 0, 0], dtype=int8)

In [52]:
b = np.ones((2,4), dtype=np.int8)
b

array([[1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int8)

In [53]:
np.empty((2,5))

array([[0.1, 0.2, 0.3, 0.4, 0.5],
       [0.6, 0.7, 0.8, 0.9, 1. ]])

In [61]:
a =np.arange(24).reshape(4,-1)
np.ones_like(a)

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

In [56]:
np.zeros_like(a)

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [60]:
# 단위 행렬: identity
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [62]:
#eye - 대각선이 1인 행렬


- Random sampleing

In [64]:
np.random.seed(2021)


#균등 분포
np.random.uniform(0, 1, 10).reshape(2,5)

array([[0.60597828, 0.73336936, 0.13894716, 0.31267308, 0.99724328],
       [0.12816238, 0.17899311, 0.75292543, 0.66216051, 0.78431013]])

In [65]:
#정규 분포
np.random.normal(0,1,10).reshape(2,5)

array([[ 0.10641374,  0.42215483,  0.12420684, -0.83795346,  0.4090157 ],
       [ 0.10275122, -1.90772239,  1.1002243 , -1.40232506, -0.22508127]])

In [66]:
# 이항분포, 포아송분포(poisson), t-분포(standard-t), f-분포(f)
np.random.binomial(100,1/6,10)

array([17, 13, 17, 16, 17, 20, 19, 11, 18, 18])

In [67]:
import numpy as np

#### Operation

In [69]:
a = np.arange(1,11,dtype=np.float32)
a.sum()

55.0

In [70]:
b = np.arange(1,11).reshape(3,4)
b

ValueError: cannot reshape array of size 10 into shape (3,4)

In [71]:
# 세로 방향의 합
b.sum(axis=0)

array([2, 2, 2, 2])

In [72]:
# 가로방향의 합
b.sum(axis=1)

array([4, 4])

In [73]:
# 평균
b.mean(axis=0),b.mean(axis=1)

(array([1., 1., 1., 1.]), array([1., 1.]))

In [74]:
#표준편차
b.std(axis=0),b.std(axis=1)

(array([0., 0., 0., 0.]), array([0., 0.]))

In [78]:
#수학함수
X = np.arange(-1,1.01,0.01)
X.size

201

In [79]:
# sigmaid 함수
Y = 1./(1. + exp(-X))

NameError: name 'exp' is not defined

In [81]:
#전치행렬(tracspose)
b.T

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1]], dtype=int8)

In [83]:
np.concatenate((a,b.T), axis=1)

AxisError: axis 1 is out of bounds for array of dimension 1

In [84]:
np.hstack((a,b.T))

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 1 dimension(s) and the array at index 1 has 2 dimension(s)

#### Array operation

In [86]:
a - a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)

In [87]:
a + a

array([ 2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.], dtype=float32)

In [88]:
a / a

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.], dtype=float32)

- dot product

In [89]:
a =np.arange(1,7),reshape(2,3)
a.dot(a.T)

NameError: name 'reshape' is not defined

In [90]:
np.dot(a,a.T)

385.0

In [91]:
a + 10

array([11., 12., 13., 14., 15., 16., 17., 18., 19., 20.], dtype=float32)

In [92]:
a * 2

array([ 2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.], dtype=float32)

In [93]:
a ** 2

array([  1.,   4.,   9.,  16.,  25.,  36.,  49.,  64.,  81., 100.],
      dtype=float32)

In [94]:
a + np.array([10, 20, 30])

ValueError: operands could not be broadcast together with shapes (10,) (3,) 

#### Comparison

In [97]:
a =np.arange(5)
np.all(a), np.any(a)

(False, True)

In [98]:
a > 2

array([False, False, False,  True,  True])

In [99]:
a[a > 2]

array([3, 4])

- Logical operation

In [101]:
a = np.arange(5)
b = np.logical_and(a>0,a<3)
b

array([False,  True,  True, False, False])

In [105]:
c = np.logical_not(b)
c

array([ True, False, False,  True,  True])

In [106]:
np.logical_or(b,c)

array([ True,  True,  True,  True,  True])

In [107]:
np.logical_xor(b,c)

array([ True,  True,  True,  True,  True])

In [108]:
a = np.arange(5)
np.where(a>2)

(array([3, 4], dtype=int64),)

- NaN(Not a Number), Int(Infinite)

In [109]:
a = np.array([1, np.NaN, np.Inf], float)
a

array([ 1., nan, inf])

In [110]:
np.isnan(a), np.isfinite(a)

(array([False,  True, False]), array([ True, False, False]))

- argmax, argmin

In [112]:
a = np.arange(6)
np.argmax(a),np.argmin(a)

(5, 0)

In [114]:
b = np.arange(12).reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [115]:
np.argmax(b, axis=0)

array([2, 2, 2, 2], dtype=int64)

In [116]:
np.argmin(b, axis= 1)

array([0, 0, 0], dtype=int64)