In [1]:
import numpy as np

In [135]:
np.arange(10,81,10).reshape(2,4)

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [136]:
m = np.arange(15).reshape(3,5)
m

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [137]:
m[1,2]

7

In [138]:
m[2,4]

14

In [139]:
m[1,1:3]

array([6, 7])

In [140]:
m[1:3,2]

array([ 7, 12])

In [141]:
[m[0,3:],m[1,3:]]

[array([3, 4]), array([8, 9])]

In [167]:
f = m.flatten()
f

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [194]:
a =f[f%3 == 0]
a

array([ 0,  3,  6,  9, 12])

In [195]:
b = f[f%4 ==1]
b

array([ 1,  5,  9, 13])

In [198]:
np.intersect1d(a,b)

array([9])

In [221]:
x = np.eye(5,k=1)
y = np.eye(5,k=0)
y2 = np.eye(5,k=0)
z = np.eye(5,k=-1)
z2 = np.eye(5,k=-1)
z3 = np.eye(5,k=-1)
oh = x+y+y2+z+z2+z3
oh

array([[2., 1., 0., 0., 0.],
       [3., 2., 1., 0., 0.],
       [0., 3., 2., 1., 0.],
       [0., 0., 3., 2., 1.],
       [0., 0., 0., 3., 2.]])

In [257]:
x = np.random.randint(0,11,size=(5,6))
x

array([[ 0,  7,  9,  0,  9,  4],
       [ 0,  7,  1,  2,  0,  5],
       [ 3,  7,  4,  1,  5,  3],
       [ 0,  1,  8,  0,  8,  7],
       [ 0,  2,  3, 10,  8,  8]])

In [258]:
np.max(x)

10

In [260]:
np.sum(x, axis=1)

array([29, 15, 23, 24, 31])

In [261]:
np.max(x, axis=1)

array([ 9,  7,  7,  8, 10])

In [262]:
np.mean(x, axis=1)

array([4.83333333, 2.5       , 3.83333333, 4.        , 5.16666667])

In [263]:
np.min(x, axis=1)

array([0, 0, 1, 0, 0])

In [268]:
a = np.array([[1,2,3,4],[46,99,100,71],[81,59,90,100]])
a

array([[  1,   2,   3,   4],
       [ 46,  99, 100,  71],
       [ 81,  59,  90, 100]])

In [270]:
np.sort(a, axis=1)

array([[  1,   2,   3,   4],
       [ 46,  71,  99, 100],
       [ 59,  81,  90, 100]])

In [276]:
import random

dice = []
for i in range(100) :
    dice.append(random.randint(1,6))
print(dice)

[1, 1, 6, 2, 3, 1, 4, 2, 4, 3, 6, 6, 4, 6, 2, 4, 3, 1, 3, 1, 6, 2, 5, 1, 1, 1, 1, 3, 6, 2, 4, 6, 6, 5, 6, 2, 4, 5, 1, 6, 3, 4, 6, 3, 3, 4, 4, 3, 3, 6, 5, 4, 1, 3, 1, 4, 3, 6, 4, 6, 3, 4, 3, 3, 1, 6, 5, 4, 6, 3, 4, 3, 1, 2, 5, 1, 6, 3, 2, 3, 4, 2, 4, 6, 1, 1, 4, 5, 3, 4, 1, 5, 4, 4, 4, 5, 3, 3, 4, 6]


In [285]:
import numpy

Dice = numpy.array(dice)
np.mean(Dice)

3.53

In [ ]:
stock = 